manifest:
  remotes:
    - name: DEV-OGRE
      url-base: https://github.com/DEV-OGRE
  projects:
    - name: zmk
      remote: DEV-OGRE
      revision: Ergo_S-1_OE
      import: app/west.yml
  self:
    path: config
